pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=0"
      - "check-success=terraform"
      - label!=work-in-progress
    actions:
      merge:
        method: merge