pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=0"
      - "check-success=terraform fmt"
      - "check-success=terraform validate"
      - "check-success=terraform plan"
      - "check-success=Pre-Commit"
      - "label!=work-in-progress"
    actions:
      merge:
        method: merge

  - name: "ask to resolve conflict"
    conditions:
      - "conflict"
      - "-closed"
    actions:
    comment:
      message: "This pull request is now in conflict. Could you fix it @{{author}}? 🙏"
      

  - name: "delete the head branch after merge"
    conditions:
      - "merged"
    actions:
    delete_head_branch: {}