pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=0"
      - "check-success=Terraform GitHub Actions"
    actions:
      merge:
        method: merge